# Generated by Django 3.2.9 on 2021-11-27 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('full_domain_name', models.CharField(max_length=25)),
                ('whois_check_result', models.BooleanField(blank=True, help_text='Does exist in whois?', null=True)),
                ('whois_check_date', models.DateField(blank=True, help_text='The date of last whois check', null=True)),
                ('request_check_result', models.BooleanField(blank=True, help_text='Does domain have site?', null=True)),
                ('request_check_date', models.DateField(blank=True, help_text='The date of last request check', null=True)),
            ],
            options={
                'ordering': ['full_domain_name'],
            },
        ),
    ]
