# Generated by Django 3.2.9 on 2022-05-21 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DomainZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='the name of Domain Zone', max_length=128)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('name', models.CharField(help_text='The full domain name', max_length=128, primary_key=True, serialize=False)),
                ('whois_check_result', models.BooleanField(blank=True, help_text='Does exist in whois?', null=True)),
                ('whois_check_date', models.DateField(blank=True, help_text='The date of last whois check', null=True)),
                ('resolve_check_result', models.BooleanField(blank=True, help_text='Can domain be resolved?', null=True)),
                ('resolve_check_date', models.DateField(blank=True, help_text='The date of last resolve attempt', null=True)),
                ('domain_zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='engine.domainzone')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
